Document: zeal
Title: Debian zeal Manual
Author: <insert document author here>
Abstract: This manual describes what zeal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zeal/zeal.sgml.gz

Format: postscript
Files: /usr/share/doc/zeal/zeal.ps.gz

Format: text
Files: /usr/share/doc/zeal/zeal.text.gz

Format: HTML
Index: /usr/share/doc/zeal/html/index.html
Files: /usr/share/doc/zeal/html/*.html
